pub struct LlamaCppActualState {
    pub model: String,
    // pub n_ctx: usize,
    // pub n_batch: usize,
    // pub n_gpu_layers: usize,
    // pub n_threads: usize,
    // pub n_predict: usize,
    // pub top_k: usize,
    // pub top_p: f32,
    // pub temp: f32,
    // pub repeat_last_n: usize,
    // pub repeat_penalty: f32,
    // pub frequency_penalty: f32,
    // pub presence_penalty: f32,
}
