import React from "react";

import { ConversationMessage } from "./ConversationMessage";

export function ConversationMessagePromptGeneratedTokens({
  inferenceAddr,
  prompt,
}: {
  inferenceAddr: string;
  prompt: string;
}) {
  return (
    <ConversationMessage>
      <strong>Prompt Generated Tokens</strong>: This is a message generated by
      the prompt system.
    </ConversationMessage>
  );
}
