import React, { useEffect } from "react";

import { type InferenceSocketClient } from "../InferenceSocketClient.interface";
import { ConversationMessage } from "./ConversationMessage";

export function ConversationMessagePromptGeneratedTokens({
  inferenceSocketClient,
  prompt,
}: {
  inferenceSocketClient: InferenceSocketClient;
  prompt: string;
}) {
  useEffect(
    function () {
      const abortController = new AbortController();

      void (async function () {
        using generateTokens = inferenceSocketClient.generateTokens({
          abortSignal: abortController.signal,
          prompt,
        });

        for await (const token of generateTokens.tokensStream()) {
          console.log(token);
        }
      })();

      return function () {
        abortController.abort();
      };
    },
    [inferenceSocketClient, prompt],
  );

  return (
    <ConversationMessage>
      <strong>Prompt Generated Tokens</strong>: This is a message generated by
      the prompt system.
    </ConversationMessage>
  );
}
