import React, { useEffect } from "react";

import { type InferenceSocketClient } from "../InferenceSocketClient.interface";
import { ConversationMessage } from "./ConversationMessage";

export function ConversationMessagePromptGeneratedTokens({
  inferenceSocketClient,
  prompt,
}: {
  inferenceSocketClient: InferenceSocketClient;
  prompt: string;
}) {
  useEffect(
    function () {
      const abortController = new AbortController();

      inferenceSocketClient.generateTokens({
        abortSignal: abortController.signal,
        prompt,
        onChunk(chunk: string) {
          console.log("Received chunk:", chunk);
        },
      });

      return function () {
        abortController.abort();
      };
    },
    [inferenceSocketClient, prompt],
  );

  return (
    <ConversationMessage>
      <strong>Prompt Generated Tokens</strong>: This is a message generated by
      the prompt system.
    </ConversationMessage>
  );
}
