# -----------------------------------------------------------------------------
# Phony targets
# -----------------------------------------------------------------------------

.PHONY: test
test: build
	cargo test

.PHONY: build
build:
	cargo build --package integration
